/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'manager' : IDL.Null, 'staff' : IDL.Null });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffRecord = IDL.Record({
  'staffId' : IDL.Text,
  'role' : Role,
  'fullName' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Time = IDL.Int;
export const Shift = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'staffId' : IDL.Text,
  'date' : Time,
  'shift' : Shift,
  'signInTime' : Time,
  'signOutTime' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({
  'staffId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const FinancialRecord = IDL.Record({
  'onlineSales' : IDL.Nat,
  'date' : Time,
  'expenses' : IDL.Nat,
  'shift' : Shift,
  'cashSales' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStaff' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateStaff' : IDL.Func([IDL.Text], [], []),
  'getAllStaff' : IDL.Func([], [IDL.Vec(StaffRecord)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [Time],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByStaff' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinancialRecordsByRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(FinancialRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordSignIn' : IDL.Func([IDL.Text, Time, Shift], [], []),
  'recordSignOut' : IDL.Func([IDL.Text, Time], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateFinancialRecord' : IDL.Func(
      [Time, Shift, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'manager' : IDL.Null, 'staff' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffRecord = IDL.Record({
    'staffId' : IDL.Text,
    'role' : Role,
    'fullName' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Time = IDL.Int;
  const Shift = IDL.Variant({ 'morning' : IDL.Null, 'evening' : IDL.Null });
  const AttendanceRecord = IDL.Record({
    'staffId' : IDL.Text,
    'date' : Time,
    'shift' : Shift,
    'signInTime' : Time,
    'signOutTime' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({
    'staffId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const FinancialRecord = IDL.Record({
    'onlineSales' : IDL.Nat,
    'date' : Time,
    'expenses' : IDL.Nat,
    'shift' : Shift,
    'cashSales' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStaff' : IDL.Func([IDL.Text, IDL.Text, Role], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateStaff' : IDL.Func([IDL.Text], [], []),
    'getAllStaff' : IDL.Func([], [IDL.Vec(StaffRecord)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [Time],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByStaff' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinancialRecordsByRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(FinancialRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordSignIn' : IDL.Func([IDL.Text, Time, Shift], [], []),
    'recordSignOut' : IDL.Func([IDL.Text, Time], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateFinancialRecord' : IDL.Func(
        [Time, Shift, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };