/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'staffId' : string,
  'date' : Time,
  'shift' : Shift,
  'signInTime' : Time,
  'signOutTime' : [] | [Time],
}
export interface FinancialRecord {
  'onlineSales' : bigint,
  'date' : Time,
  'expenses' : bigint,
  'shift' : Shift,
  'cashSales' : bigint,
}
export type Role = { 'manager' : null } |
  { 'staff' : null };
export type Shift = { 'morning' : null } |
  { 'evening' : null };
export interface StaffRecord {
  'staffId' : string,
  'role' : Role,
  'fullName' : string,
  'isActive' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'staffId' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStaff' : ActorMethod<[string, string, Role], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateStaff' : ActorMethod<[string], undefined>,
  'getAllStaff' : ActorMethod<[], Array<StaffRecord>>,
  'getAttendanceByDate' : ActorMethod<[Time], Array<AttendanceRecord>>,
  'getAttendanceByStaff' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFinancialRecordsByRange' : ActorMethod<
    [Time, Time],
    Array<FinancialRecord>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordSignIn' : ActorMethod<[string, Time, Shift], undefined>,
  'recordSignOut' : ActorMethod<[string, Time], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFinancialRecord' : ActorMethod<
    [Time, Shift, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];